### ISSUE TITLE
Node v0.11.3 syntax error

### ISSUE THREAD

**Issue by JustinDrake** [creationix/gen-run#1]
I have tried running the following example in node v0.11.3 with the flags `--harmony --use-strict` (prompted by [this tweet](https://twitter.com/creationix/status/351822762970595329)), but I get a syntax error `Unexpected token *`. What does "full support for harmony generators" really mean?

```
var run = require('gen-run');

run(function* () {
  console.log("Hello");
  yield sleep(1000);
  console.log("World");
});
```

**Comment by creationix** [comment]
For whatever reason, `--harmony` no longer includes generators.  You need to pass in `--harmony_generators`.
