### ISSUE TITLE
Generators stop after a caught exception

### ISSUE THREAD

**Issue by chuckjaz** [creationix/gen-run#5]
Consider the following program:

```
var run = require('gen-run');

function tick(callback) {
    process.nextTick(function() {
        callback();
    });
}

function error(callback) {
    callback(new Error());
}

function *throws() {
    yield tick;
    yield error;
}

function *catches() {
    try {
        console.log('before throws')
        yield *throws();
        console.log('after throws')
    }
    catch (err) {
        console.log('in catch')
    }
    yield tick;
    return 'Something';
}

function *tests() {
    var a = yield *catches();
    console.log('catches returned: ' + a)
}

run(tests);
```

It should display:

```
before throws
in catch
catches returned: Something
```

but the last line is not printed because the generator stops after the throw. I suspect it is because of the `if (err) return iterator.throw(err);` unconditionally stops iteration. If the generator has a catch `throw()` acts like `next()`.

Note that the `yield tick;` in `catches()` is important as it forces the generator to require an `next()` call after a `throw()` for correct operation.

**Comment by creationix** [comment]
Thanks for the report, I was wondering about this case, but never had a chance to test it out.  I'll fix this when I'm back at my desk.
